version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_SCHEMA: toursdb
      DATABASE_SCHEMA_NAME: public
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: secret
      DATABASE_INTEGRATED_SECURITY: false
      DATABASE_POOLING: true
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: toursdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

volumes:
  pgdata:
